import { v4 as uuid } from 'uuid';

// Direct-embed friendly luxury perfume photography (Unsplash)
const IMG = {
  noir: 'https://images.unsplash.com/photo-1643797519086-cc9a821fbcfe?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  argent: 'https://images.unsplash.com/photo-1610461888750-10bfc601b874?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  fumee: 'https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  cuir: 'https://images.unsplash.com/photo-1643797517590-c44cb552ddcc?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  rose: 'https://images.unsplash.com/photo-1583442801251-5ce051ed7cb3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  ambre: 'https://images.unsplash.com/photo-1598634222670-87c5f558119c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
};

export const SEED_PRODUCTS = [
  {
    slug: 'noir-obscur',
    name: 'Noir Obscur',
    brand: 'VENTEBEAST',
    shortDescription: 'A liquid shadow. Smoked oud, bitter leather, and black incense.',
    description: 'NOIR OBSCUR is a study in darkness. Built around a heart of Cambodian oud and Mysore sandalwood, it unfurls slowly across the skin like silk dragged through smoke. Top notes of black pepper and bergamot give way to a smoldering core of leather, saffron, and dried tobacco. The base is a long, low whisper of vetiver, labdanum, and ambergris that lingers for over twelve hours.',
    category: 'Extrait',
    collection: 'Signature',
    gender: 'Unisex',
    concentration: 'Extrait de Parfum',
    topNotes: ['Black Pepper', 'Bergamot', 'Saffron'],
    heartNotes: ['Cambodian Oud', 'Leather', 'Tobacco'],
    baseNotes: ['Vetiver', 'Labdanum', 'Ambergris'],
    longevity: '12+ hours', projection: 'Heavy', scentFamily: 'Woody Oriental',
    featured: true, bestseller: true, newArrival: false,
    rating: 4.9, reviewCount: 127,
    images: [IMG.noir],
    variants: [
      { size: '30ml', sku: 'NOR-30', price: 4800, comparePrice: 5600, stock: 25 },
      { size: '50ml', sku: 'NOR-50', price: 7200, comparePrice: 8400, stock: 18 },
      { size: '100ml', sku: 'NOR-100', price: 11800, comparePrice: 13600, stock: 12 },
    ],
  },
  {
    slug: 'argent-eclat',
    name: 'Argent Éclat',
    brand: 'VENTEBEAST',
    shortDescription: 'Cold silver, iris suede, and a knife-edge of metallic violet.',
    description: 'ARGENT ÉCLAT captures the moment moonlight strikes polished steel. Aldehydes and iris pallida open with a glacial brightness, supported by violet leaf and orris butter. The drydown reveals a sleek suede accord and powdered ambrette.',
    category: 'Eau de Parfum', collection: 'Metallics', gender: 'Unisex', concentration: 'Eau de Parfum',
    topNotes: ['Aldehydes', 'Bergamot', 'Violet Leaf'],
    heartNotes: ['Iris Pallida', 'Orris Butter', 'Ambrette'],
    baseNotes: ['Suede', 'White Musk', 'Cashmeran'],
    longevity: '9 hours', projection: 'Moderate', scentFamily: 'Powdery Floral',
    featured: true, bestseller: false, newArrival: true,
    rating: 4.8, reviewCount: 84,
    images: [IMG.argent],
    variants: [
      { size: '30ml', sku: 'ARG-30', price: 4200, comparePrice: 4900, stock: 30 },
      { size: '50ml', sku: 'ARG-50', price: 6400, comparePrice: 7400, stock: 22 },
      { size: '100ml', sku: 'ARG-100', price: 10400, comparePrice: 12000, stock: 15 },
    ],
  },
  {
    slug: 'fume-sacre',
    name: 'Fumée Sacrée',
    brand: 'VENTEBEAST',
    shortDescription: 'Frankincense cathedrals, myrrh resin, and burnt cedar embers.',
    description: 'FUMÉE SACRÉE is the scent of an empty stone chapel an hour after the censer has swung. Olibanum and myrrh smolder over papyrus and dry cedarwood, with a faint sweetness of benzoin in the deep base.',
    category: 'Extrait', collection: 'Sacred', gender: 'Unisex', concentration: 'Extrait de Parfum',
    topNotes: ['Olibanum', 'Pink Pepper', 'Elemi'],
    heartNotes: ['Myrrh', 'Papyrus', 'Cypress'],
    baseNotes: ['Benzoin', 'Cedarwood', 'Guaiac Wood'],
    longevity: '10 hours', projection: 'Moderate', scentFamily: 'Resinous Woody',
    featured: true, bestseller: true, newArrival: false,
    rating: 4.9, reviewCount: 156,
    images: [IMG.fumee],
    variants: [
      { size: '30ml', sku: 'FUM-30', price: 5200, comparePrice: 6000, stock: 20 },
      { size: '50ml', sku: 'FUM-50', price: 7800, comparePrice: 9000, stock: 14 },
      { size: '100ml', sku: 'FUM-100', price: 12600, comparePrice: 14500, stock: 8 },
    ],
  },
  {
    slug: 'cuir-volcanique',
    name: 'Cuir Volcanique',
    brand: 'VENTEBEAST',
    shortDescription: 'Hot black leather, basalt, and a curl of birch tar smoke.',
    description: 'CUIR VOLCANIQUE is a brutalist leather: dense, mineral, and faintly animalic. Birch tar and styrax form the spine; castoreum and labdanum amplify the warmth.',
    category: 'Eau de Parfum', collection: 'Leathers', gender: 'Unisex', concentration: 'Eau de Parfum',
    topNotes: ['Birch Tar', 'Cade', 'Saffron'],
    heartNotes: ['Black Leather', 'Styrax', 'Cumin'],
    baseNotes: ['Castoreum', 'Labdanum', 'Vetiver'],
    longevity: '11 hours', projection: 'Heavy', scentFamily: 'Leather',
    featured: false, bestseller: true, newArrival: false,
    rating: 4.7, reviewCount: 92,
    images: [IMG.cuir],
    variants: [
      { size: '30ml', sku: 'CUI-30', price: 4600, comparePrice: 5400, stock: 22 },
      { size: '50ml', sku: 'CUI-50', price: 6900, comparePrice: 8000, stock: 16 },
      { size: '100ml', sku: 'CUI-100', price: 11200, comparePrice: 12900, stock: 10 },
    ],
  },
  {
    slug: 'rose-de-minuit',
    name: 'Rose de Minuit',
    brand: 'VENTEBEAST',
    shortDescription: 'Bulgarian rose absolute, black plum, and burnt cocoa.',
    description: 'ROSE DE MINUIT reimagines rose at the witching hour. Damascena absolute soaked in black plum sits over a dark cocoa-and-patchouli foundation. Not a feminine rose. A nocturnal one.',
    category: 'Eau de Parfum', collection: 'Florals Noir', gender: 'Unisex', concentration: 'Eau de Parfum',
    topNotes: ['Black Plum', 'Pink Pepper', 'Litchi'],
    heartNotes: ['Bulgarian Rose', 'Damascena', 'Geranium'],
    baseNotes: ['Cocoa Absolute', 'Patchouli', 'Oud'],
    longevity: '10 hours', projection: 'Heavy', scentFamily: 'Floral Gourmand',
    featured: true, bestseller: false, newArrival: true,
    rating: 4.8, reviewCount: 71,
    images: [IMG.rose],
    variants: [
      { size: '30ml', sku: 'ROS-30', price: 4400, comparePrice: 5100, stock: 28 },
      { size: '50ml', sku: 'ROS-50', price: 6700, comparePrice: 7700, stock: 20 },
      { size: '100ml', sku: 'ROS-100', price: 10800, comparePrice: 12500, stock: 13 },
    ],
  },
  {
    slug: 'ambre-celeste',
    name: 'Ambre Céleste',
    brand: 'VENTEBEAST',
    shortDescription: 'Liquid amber, vanilla orchid, and a thread of incense.',
    description: 'AMBRE CÉLESTE is an unapologetic amber. Tonka, benzoin, and Madagascar vanilla layered over a resinous heart of labdanum and frankincense.',
    category: 'Extrait', collection: 'Ambres', gender: 'Unisex', concentration: 'Extrait de Parfum',
    topNotes: ['Bergamot', 'Cardamom', 'Pink Pepper'],
    heartNotes: ['Labdanum', 'Frankincense', 'Orchid'],
    baseNotes: ['Tonka Bean', 'Madagascar Vanilla', 'Benzoin'],
    longevity: '12+ hours', projection: 'Heavy', scentFamily: 'Amber Oriental',
    featured: true, bestseller: true, newArrival: false,
    rating: 4.9, reviewCount: 203,
    images: [IMG.ambre],
    variants: [
      { size: '30ml', sku: 'AMB-30', price: 5400, comparePrice: 6200, stock: 24 },
      { size: '50ml', sku: 'AMB-50', price: 8100, comparePrice: 9400, stock: 17 },
      { size: '100ml', sku: 'AMB-100', price: 13200, comparePrice: 15200, stock: 9 },
    ],
  },
];

export const HERO_IMAGES = IMG;

export function buildSeedDocs() {
  const now = new Date();
  return SEED_PRODUCTS.map((p) => ({ _id: uuid(), ...p, gallery: p.images, createdAt: now, updatedAt: now }));
}
